-- create the database
CREATE DATABASE IF NOT EXISTS INOCULYST;
USE INOCULYST;


----- USER / ROLE TABLES ------
-- table: ADMIN
CREATE TABLE IF NOT EXISTS ADMIN (
  ID CHAR(10) NOT NULL,
  First_name VARCHAR(20),
  Last_name VARCHAR(20) NOT NULL,
  Email VARCHAR(20),
  Phone_Number CHAR(10),
  PRIMARY KEY(ID)
);

-- table: EMPLOYEE
CREATE TABLE IF NOT EXISTS EMPLOYEE (
  ID CHAR(10) NOT NULL,
  First_name VARCHAR(20),
  Last_name VARCHAR(20) NOT NULL,
  Email VARCHAR(20),
  Phone_number CHAR(10),
  PRIMARY KEY(ID)
);

-- table: ACCOUNT
CREATE TABLE IF NOT EXISTS ACCOUNT (
  ID CHAR(10) NOT NULL,
  Account_type VARCHAR(10) NOT NULL,
  Username VARCHAR(20) NOT NULL,
  -- Password VARCHAR(20) NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(ID) REFERENCES ADMIN(ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(ID) REFERENCES EMPLOYEE(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- table: OWNER
CREATE TABLE IF NOT EXISTS OWNER (
  Owner_ID CHAR(10) NOT NULL,
  ID CHAR(10) NOT NULL,
  PRIMARY KEY(Owner_ID),
  FOREIGN KEY(Owner_ID) REFERENCES ADMIN(ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(ID) REFERENCES ACCOUNT(ID) ON UPDATE CASCADE
);

-- table: PHARMACIST
CREATE TABLE IF NOT EXISTS PHARMACIST (
  Pharmacist_ID CHAR(10) NOT NULL,
  Specialty VARCHAR(20) NOT NULL,
  PRIMARY KEY(Pharmacist_ID),
  FOREIGN KEY(Pharmacist_ID) REFERENCES ADMIN(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- table: TECHNICIAN
CREATE TABLE IF NOT EXISTS TECHNICIAN (
  Technician_ID CHAR(10) NOT NULL,
  Certification_number CHAR(10) NOT NULL,
  PRIMARY KEY(Technician_ID),
  FOREIGN KEY(Technician_ID) REFERENCES EMPLOYEE(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- table: ASSISTANT
CREATE TABLE IF NOT EXISTS ASSISTANT (
  Assistant_ID CHAR(10) NOT NULL,
  PRIMARY KEY(Assistant_ID),
  FOREIGN KEY(Assistant_ID) REFERENCES EMPLOYEE(ID) ON DELETE CASCADE ON UPDATE CASCADE
);


-- run this to initalize: mysql -u root -p < database/migrations/init.sql
-- (don't run it right now)